
name: Rewards Action

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
       pip install -r requirements.txt
    - name: Main ID
      run: |
        python MicrosoftRewardsBot.py --headless --fast --emailalerts
        
      #Credentials will store in accounts.json file
# Normal Workflow will run for 20Min if normal Single ID & 40 if 2 Accounts 
# --emailalerts will send user mail if account gets locked or banned 
    - name: Save logs.txt as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: logs.txt
